language: go

go:
  - 1.1
  - 1.2
  - 1.3
  - tip

install:
  - go get github.com/stretchr/testify/assert
  - go get github.com/gorilla/websocket
  - go get github.com/qlm-iot/qlm/df
  - go get github.com/qlm-iot/qlm/mi

script:
  - go test ./...